### ISSUE TITLE
Enum values are treated as Objects

### ISSUE THREAD

**Issue by yeshodhan** [Orange-OpenSource/angular-swagger-ui#42] opened 2016-03-07 23:11 UTC
Enum values are rendered and treated as objects.

Eg:

``` json
"definitions":{
   "Gender" : {
      "enum" : ["Male", "Female"],
      "type" : "string",
      "title" : "Gender"
   },
   "Person" : {
      "type" : "object",
      "title" : "Person",
      "properties":{
            "gender":{
                "$ref" : "#/definitions/Gender"             
        }
      }
   }
}
```

When this is rendered and the object is generated for person, enum property is being rendered as:

``` json
{
   "gender":{}
}
```

Instead, they should be displayed as: 

``` json
{
   "gender":"string"
}
```

**Comment by mathieuales** [comment] 2016-03-08 10:30
Hi !
I can't reproduce the issue : take a look at http://orange-opensource.github.io/angular-swagger-ui/ the operation `POST /store/order` contains enum and is displayed as requested ...
Please make sure to use latest version and if issue still present please send a full swagger descriptor

**Comment by mathieuales** [comment] 2016-06-06 14:54
closed as no answer recieved

**Closed as completed by mathieuales** 2016-06-06 14:54 UTC
Labels: bug
