### ISSUE TITLE
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed (Fix)

### ISSUE THREAD

**Issue by bSm1le** [Orange-OpenSource/angular-swagger-ui#17] opened 2015-08-18 10:28 UTC
Updated to swagger 0.2.1 and I am getting an Error like this:
![ngrepeatdupe](https://cloud.githubusercontent.com/assets/13848610/9326596/280a5c04-459b-11e5-919e-94a1427ae91b.jpg)

Had to change 1 thing in line 665 at /dist/scripts/swagger-ui.js

```
// parse resources
            if (!swagger.tags) {
                resources.push({
                    name: 'default',
                    open: true
                });
                map['default'] = 0;
            }
```

to this:

```
// parse resources
            if (swagger.tags) {
                resources.push({
                    name: 'default',
                    open: true
                });
                map['default'] = 0;
            }
```

**Comment by mathieuales** [comment] 2015-08-18 13:17
Hi !
This should not be the way to fix the issue ...
Do you mind sending your swagger descriptor as i can't reproduce using my samples?

**Comment by bSm1le** [comment] 2015-08-18 14:35
http://ntrc-delta.neoteric.eu:9000/api/neodocs/swagger.json

**Comment by mathieuales** [comment] 2015-08-18 14:47
Can't reproduce the issue with your file on the demo: http://orange-opensource.github.io/angular-swagger-ui/
Could you please show how you use the component ?

**Comment by bodinegl** [comment] 2015-08-20 14:04
actually I am having the very same issue but only when I use the swagger-ui directive in a partial as part of a singe page app.  if I put it in the index.html page like your example it works fine.

**Comment by mathieuales** [comment] 2015-08-21 13:13
should be fixed in 0.2.2, can you confirm ?

**Comment by bodinegl** [comment] 2015-08-21 14:46
0.2.2 did fix the ngRepeat:dupes error but now I have a new issue.  every
time I hit the "open/hide", "list operations", "expand operations" buttons
I get two additional duplicate operations in the list.  (see attached).
 there should only be one.  I also see the "error{}" now, which use to be
verify.

thanks
--greg

swagger doc:

{"info": {"version": "1.0.0", "contact": {"name":
"bodinegl@gmail.com"}, "description": "#### base connectors return the
contents of a file\n", "license": {"url":
"http://www.test.com/legal/license-agreements.aspx", "name": "Test
Inc."}, "title": "Base - Cloud Connectors", "copyright": "2015 Test
Inc. ALL RIGHTS RESERVED"}, "paths": {"/base": {"get": {"description":
"base connector description for get verb", "tags": ["base"],
"summary": "base connector summary for get verb", "responses": {"200":
{"description": "successful operation"}}, "produces":
["application/json"]}}}, "schemes": ["http"], "produces":
["application/json"], "basePath": "/connector", "tags": [{"name":
"base", "description": "base connector"}], "host": "localhost:8080",
"swagger": "2.0"}

[image: Inline images 1]

when I click the "error {}" I see the following:

[{"level":"error","message":"Can't read from file
http://localhost:8080/connectors/base"}]

but if I go to that link directly I get the swagger doc back like above.

**Comment by mathieuales** [comment] 2015-08-24 07:23
I finally reproduced the issue when using 'ngRoute'. If you do so, you can fix the issue by adding reloadOnSearch = false in your route configuration

**Closed as completed** 2015-08-25 15:56 UTC
Labels: bug
