### ISSUE TITLE
Basepath Problem

### ISSUE THREAD

**Issue by samypr100** [Orange-OpenSource/angular-swagger-ui#46] opened 2016-04-01 14:47 UTC
This issue is about swagger spec and base path behavior.
Using this library if you set it to "/" (meaning root), it's appending a "/" to the end of the url resulting in `http(s)://host:port/apiRoute//...` it should be `http(s)://host:port/apiRoute/...`
Instead if it's not simply "/", and something like "/basepath/" it's correct to append a "/" on the end if it doesn't exist.
I don't have this issue with swagger-ui itself, hence I though I should bring it up.

**Comment by daniel-cotton** [comment] 2016-11-30 10:51
Should be able to close now - addressed in #58

**Comment by anil2** [comment] 2016-12-06 08:40
I see that the problem is addressed and solved, may I know when will it be available in release? I see that the packages downloaded via bower still have the old version. Thanks.

**Closed as completed** 2016-12-15 11:11 UTC
Labels: bug
