### ISSUE TITLE
Swagger UI page unresponsive for large swagger json

### ISSUE THREAD

**Issue by nijinillath** [Orange-OpenSource/angular-swagger-ui#94] opened 2018-09-25 09:55 UTC
Hi Team,

I have the swagger json with multiple complex model elements and services collectively sized almost 1.7MB. The swagger generated code is in jersey 2.0.
I am using the latest angular-swagger-ui which is deployed with my server under webapps, but while loading the services from swagger ui the ui page is getting unresponsive, is there any performance improvement can be done for larger swagger json ?

Thanks

**Comment by mathieuales** [comment] 2018-10-01 15:08
Hi !
Do you mind giving an access to your swagger json so i can see what's happening?
Regards

**Comment by nijinillath** [comment] 2018-10-04 06:35
Sure @mathieuales 
As this is hosted in a secured proxy server, is there any way i can share this modified json file via email or other options ?

**Comment by mathieuales** [comment] 2018-10-04 08:18
You can attach files to github comments using drag'n'drop

**Comment by nijinillath** [comment] 2018-10-26 04:53
Hi @mathieuales , Sorry for the delay in the response.

Attaching the swagger json we are facing performance issue specifically while loading services having complex models elements like "/complete" , "/rates".

[swagger.txt](https://github.com/Orange-OpenSource/angular-swagger-ui/files/2517737/swagger.txt)

Thanks in advance..

**Comment by mathieuales** [comment] 2018-10-31 12:49
Hi!
Unfortunately there is not much to do, your models are very huge!! 
I tried different things and got it a bit better but nothing acceptable. Generating samples and models takes time and generates large HTML which takes time to render with angularJS.
The result is the same or maybe worse using official [swaggerUI](https://petstore.swagger.io) as it is unable to render models.
My advise is you should maybe consider redesigning your API as exposing such huge models does not seem to be a good pratice.
Regards

**Comment by mathieuales** [comment] 2019-01-10 09:56
duplicate of #77

**Closed as completed by mathieuales** 2019-01-10 09:56 UTC
Labels: duplicate
